// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Schedule.Api.Data;

#nullable disable

namespace Schedule.Api.Migrations
{
    [DbContext(typeof(ScheduleDbContext))]
    [Migration("20260315122024_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Schedule.Api.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresSpecialRoom")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorCode = "#ef4444",
                            Name = "國文",
                            RequiresSpecialRoom = false
                        },
                        new
                        {
                            Id = 2,
                            ColorCode = "#3b82f6",
                            Name = "英語",
                            RequiresSpecialRoom = false
                        },
                        new
                        {
                            Id = 3,
                            ColorCode = "#22c55e",
                            Name = "數學",
                            RequiresSpecialRoom = false
                        },
                        new
                        {
                            Id = 4,
                            ColorCode = "#f59e0b",
                            Name = "社會",
                            RequiresSpecialRoom = false
                        },
                        new
                        {
                            Id = 5,
                            ColorCode = "#8b5cf6",
                            Name = "自然科學",
                            RequiresSpecialRoom = false
                        },
                        new
                        {
                            Id = 6,
                            ColorCode = "#06b6d4",
                            Name = "科技",
                            RequiresSpecialRoom = false
                        },
                        new
                        {
                            Id = 7,
                            ColorCode = "#ec4899",
                            Name = "藝術",
                            RequiresSpecialRoom = false
                        },
                        new
                        {
                            Id = 8,
                            ColorCode = "#14b8a6",
                            Name = "健康與體育",
                            RequiresSpecialRoom = true
                        },
                        new
                        {
                            Id = 9,
                            ColorCode = "#f97316",
                            Name = "綜合活動",
                            RequiresSpecialRoom = false
                        },
                        new
                        {
                            Id = 10,
                            ColorCode = "#64748b",
                            Name = "彈性學習",
                            RequiresSpecialRoom = false
                        });
                });

            modelBuilder.Entity("Schedule.Api.Models.CourseAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SemesterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeeklyPeriods")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("CourseId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("SemesterId", "CourseId", "ClassId")
                        .IsUnique();

                    b.ToTable("CourseAssignments");
                });

            modelBuilder.Entity("Schedule.Api.Models.HomeroomAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SemesterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("SemesterId", "ClassId")
                        .IsUnique();

                    b.HasIndex("SemesterId", "TeacherId")
                        .IsUnique();

                    b.ToTable("HomeroomAssignments");
                });

            modelBuilder.Entity("Schedule.Api.Models.Period", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("PeriodNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SemesterId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SemesterId", "PeriodNumber")
                        .IsUnique();

                    b.ToTable("Periods");
                });

            modelBuilder.Entity("Schedule.Api.Models.RoomBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpecialRoomId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimetableSlotId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SpecialRoomId");

                    b.HasIndex("TimetableSlotId")
                        .IsUnique();

                    b.ToTable("RoomBookings");
                });

            modelBuilder.Entity("Schedule.Api.Models.SchoolClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GradeYear")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HomeroomAssignmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Section")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SemesterId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HomeroomAssignmentId");

                    b.HasIndex("SemesterId", "GradeYear", "Section")
                        .IsUnique();

                    b.ToTable("SchoolClasses");
                });

            modelBuilder.Entity("Schedule.Api.Models.SchoolDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SemesterId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SemesterId", "DayOfWeek")
                        .IsUnique();

                    b.ToTable("SchoolDays");
                });

            modelBuilder.Entity("Schedule.Api.Models.Semester", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AcademicYear")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Term")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AcademicYear", "Term")
                        .IsUnique();

                    b.ToTable("Semesters");
                });

            modelBuilder.Entity("Schedule.Api.Models.SpecialRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SpecialRooms");
                });

            modelBuilder.Entity("Schedule.Api.Models.StaffTitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StaffTitles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "專任教師"
                        },
                        new
                        {
                            Id = 2,
                            Name = "代理教師"
                        },
                        new
                        {
                            Id = 3,
                            Name = "代課教師"
                        });
                });

            modelBuilder.Entity("Schedule.Api.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxWeeklyPeriods")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StaffTitleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StaffTitleId");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("Schedule.Api.Models.TimetableSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseAssignmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PeriodId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PeriodId");

                    b.HasIndex("CourseAssignmentId", "DayOfWeek", "PeriodId")
                        .IsUnique();

                    b.ToTable("TimetableSlots");
                });

            modelBuilder.Entity("Schedule.Api.Models.CourseAssignment", b =>
                {
                    b.HasOne("Schedule.Api.Models.SchoolClass", "Class")
                        .WithMany("CourseAssignments")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Schedule.Api.Models.Course", "Course")
                        .WithMany("CourseAssignments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Schedule.Api.Models.Semester", "Semester")
                        .WithMany("CourseAssignments")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Schedule.Api.Models.Teacher", "Teacher")
                        .WithMany("CourseAssignments")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Course");

                    b.Navigation("Semester");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Schedule.Api.Models.HomeroomAssignment", b =>
                {
                    b.HasOne("Schedule.Api.Models.SchoolClass", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Schedule.Api.Models.Semester", "Semester")
                        .WithMany("HomeroomAssignments")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Schedule.Api.Models.Teacher", "Teacher")
                        .WithMany("HomeroomAssignments")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Semester");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Schedule.Api.Models.Period", b =>
                {
                    b.HasOne("Schedule.Api.Models.Semester", "Semester")
                        .WithMany("Periods")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("Schedule.Api.Models.RoomBooking", b =>
                {
                    b.HasOne("Schedule.Api.Models.SpecialRoom", "SpecialRoom")
                        .WithMany("RoomBookings")
                        .HasForeignKey("SpecialRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Schedule.Api.Models.TimetableSlot", "TimetableSlot")
                        .WithOne("RoomBooking")
                        .HasForeignKey("Schedule.Api.Models.RoomBooking", "TimetableSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpecialRoom");

                    b.Navigation("TimetableSlot");
                });

            modelBuilder.Entity("Schedule.Api.Models.SchoolClass", b =>
                {
                    b.HasOne("Schedule.Api.Models.HomeroomAssignment", "HomeroomAssignment")
                        .WithMany()
                        .HasForeignKey("HomeroomAssignmentId");

                    b.HasOne("Schedule.Api.Models.Semester", "Semester")
                        .WithMany("Classes")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HomeroomAssignment");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("Schedule.Api.Models.SchoolDay", b =>
                {
                    b.HasOne("Schedule.Api.Models.Semester", "Semester")
                        .WithMany("SchoolDays")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("Schedule.Api.Models.Teacher", b =>
                {
                    b.HasOne("Schedule.Api.Models.StaffTitle", "StaffTitle")
                        .WithMany("Teachers")
                        .HasForeignKey("StaffTitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StaffTitle");
                });

            modelBuilder.Entity("Schedule.Api.Models.TimetableSlot", b =>
                {
                    b.HasOne("Schedule.Api.Models.CourseAssignment", "CourseAssignment")
                        .WithMany("TimetableSlots")
                        .HasForeignKey("CourseAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Schedule.Api.Models.Period", "Period")
                        .WithMany("TimetableSlots")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseAssignment");

                    b.Navigation("Period");
                });

            modelBuilder.Entity("Schedule.Api.Models.Course", b =>
                {
                    b.Navigation("CourseAssignments");
                });

            modelBuilder.Entity("Schedule.Api.Models.CourseAssignment", b =>
                {
                    b.Navigation("TimetableSlots");
                });

            modelBuilder.Entity("Schedule.Api.Models.Period", b =>
                {
                    b.Navigation("TimetableSlots");
                });

            modelBuilder.Entity("Schedule.Api.Models.SchoolClass", b =>
                {
                    b.Navigation("CourseAssignments");
                });

            modelBuilder.Entity("Schedule.Api.Models.Semester", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("CourseAssignments");

                    b.Navigation("HomeroomAssignments");

                    b.Navigation("Periods");

                    b.Navigation("SchoolDays");
                });

            modelBuilder.Entity("Schedule.Api.Models.SpecialRoom", b =>
                {
                    b.Navigation("RoomBookings");
                });

            modelBuilder.Entity("Schedule.Api.Models.StaffTitle", b =>
                {
                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("Schedule.Api.Models.Teacher", b =>
                {
                    b.Navigation("CourseAssignments");

                    b.Navigation("HomeroomAssignments");
                });

            modelBuilder.Entity("Schedule.Api.Models.TimetableSlot", b =>
                {
                    b.Navigation("RoomBooking");
                });
#pragma warning restore 612, 618
        }
    }
}
